Update 220215_TIL.md
Error: "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0.
ERROR in Error while loading rule '@typescript-eslint/await-thenable': You have used a rule which requires  the "parserOptions.project" property for @typescript-eslint/parser.